name: Deploy to GCP on tag push

on:
  push:
    branches:    
      - 'main'
env:
  #GOOGLE_PROJECT_ID_DEV: ${{ secrets.GKE_PROJECT }}
  #GOOGLE_PROJECT_ID_TEST: ${{ secrets.GKE_TEST_PROJECT }}
  #GOOGLE_PROJECT_ID_PROD: ${{ secrets.GKE_PROD_PROJECT }}
  #GCLOUD_SERVICE_KEY_DEV: ${{ secrets.GKE_SA_KEY }}
  #GCLOUD_SERVICE_KEY_TEST: ${{ secrets.GKE_SA_KEY_TEST }}
  #GCLOUD_SERVICE_KEY_PROD: ${{ secrets.GKE_SA_KEY_PROD }}
  GKE_CLUSTER: aaap-platform-cluster
  GKE_ZONE: europe-west6-a
  IMAGE: people-management-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Determine the environment name
      - name: Determine the environment name
        run: |-
          GITHUB_ACTIONS_TAG=${GITHUB_REF:10}
          ENVIRONMENT_LOWERCASE=$(echo $GITHUB_ACTIONS_TAG | sed s/-deploy//g)
          ENVIRONMENT=$(echo $ENVIRONMENT_LOWERCASE | tr a-z A-Z)
          echo "ENVIRONMENT is $ENVIRONMENT"
          echo "ENVIRONMENT_LOWERCASE=${ENVIRONMENT_LOWERCASE}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV
          echo "GITHUB_ACTIONS_TAG=${GITHUB_ACTIONS_TAG}" >> $GITHUB_ENV
